### PR TITLE
WIP infinite crawl, flat files to DB

### PR DESCRIPTION
**Pull request by leonstafford**
per https://github.com/WP2Static/static-html-output-plugin/issues/85

### CODE REVIEW

**Comment by leonstafford** [comment]
@thegulshankumar this may be of interest to check:

 - all URLs detected during crawl
 - code output looks OK

Note: it's only tested with ZIP deployment at the moment, others may not work (won't show progress at least)

[static-html-output-plugin-wip-zip-only.zip](https://github.com/WP2Static/static-html-output-plugin/files/4775033/static-html-output-plugin-wip-zip-only.zip)

Sitting down too long, will take a break and start on the other deployers

**Comment by thegulshankumar** [comment]
Tried, unable to save options.

**Comment by leonstafford** [comment]
@thegulshankumar thanks for checking - also shows me some UI issues when smaller screen size!

Are you getting some browser console errors or server errors with that?

**Comment by thegulshankumar** [comment]
There was little timeout issue but I could fix by adding

```
fastcgi_read_timeout 10800;
```

**Pull request merged**
