### PR TITLE
Add progress output to CLI "generate" command

### PR DESCRIPTION
**Pull request by crstauf**
I was [also surprised](https://github.com/WP2Static/static-html-output-plugin/issues/77#issue-629368258) that the `generate` CLI command did not have progress output; this PR adds various logs and (hopefully accurate) progress bars to the output while the command moves through each step.

### CODE REVIEW

**Comment by leonstafford** [comment]
Nice~!

I'll need to check the usage of WP_CLI's progress from within other classes (vs the src\CLI class). I had some issues prior with PHPStan not accepting the progress bar being instantiated/called from elsewhere...

Just going to sleep, but will be back onto things tomorrow

**Comment by leonstafford** [comment]
@crstauf sleep could wait a bit - I was too curious :P

I checked out a patch of yours into a temp branch and made a few changes to appease phpcs and PHPStan:

https://github.com/WP2Static/static-html-output-plugin/commit/a6761c96838aadd93b2a32573209566cf8418fed

I think it just needs an extra check to only do the WP_CLI progress stuff when running via CLI - there's some other methods scattered around code doing something to check that.

If you can run `composer test` against your branch, you should see the same errors I did ( I need to fix up circleci integration with Pull Requests to automate that).

**Comment by leonstafford** [comment]
PS. the issue with running WP_CLI commands outside the CLI class is no longer an issue - maybe some updates to the code checkers or change of CLI class since I encountered that, so all good to go once it can merge in 🎈

**Comment by crstauf** [comment]
> I think it just needs an extra check to only do the WP_CLI progress stuff when running via CLI

@leonstafford These should already be in place: the `progress_bar` property is only set if `WP_CLI` is defined, and uses check if `progress_bar` property is non-empty.

**Comment by leonstafford** [comment]
@crstauf Beautiful! Many thanks for contributing this!

**Comment by crstauf** [comment]
Welcome! 🙇‍♂️

**Pull request merged**
